# Custom Language File for Launcher Customizer

[ejs.app]
title = "MDXU Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/gabidut/mdxu-launcher
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/gabidut/mdxu-launcher"
supportLink = "https://github.com/gabidut/mdxu-launcher"

[ejs.welcome]
welcomeHeader = "Bienvenue sur le launcher de MDX-Universe"
welcomeDescription = ""
welcomeDescCTA = ""
